steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: graphql-explorer
        image-repository: index.docker.io/buildkiteci/graphql-explorer
    env:
      NODE_ENV: development
    agents:
      queue: elastic-builders

  - wait

  - name: ":webpack:"
    command: ".buildkite/webpack.sh"
    artifact_paths: "dist/**/*"
    plugins:
      docker-compose#e8ce6c1:
        run: graphql-explorer

  - wait

  - name: ":shipit:"
    command: ".buildkite/deploy.sh"
    branches: "master"
    agents:
      queue: "deploy"
